apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: try-pipeline
  description: A component linked to the Jenkins pipeline named 'try'.
  annotations:
    jenkins.io/job-full-name: "try"
    # Example optional annotations for other plugins:
    # github.com/project-slug: your-org/your-repo
    # backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
